services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: ft_transcendence
    ports:
      - "3000:3000"
<<<<<<<< HEAD:docker-compose.yml
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

    restart: unless-stopped
========
    command: npm run dev
    restart: unless-stopped
>>>>>>>> main:srcs/docker-compose.yml
