version: '3.8'

services:
  web:
    build:
      context: .
    image: ft_transcendence
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

    restart: unless-stopped