version: '3.8'

services:
  web:
    build:
    context: .
    image: ft_transcendence
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    restart: unless-stopped

  nginx:
    images: owasp/modsecurity-crs:nginx
    ports:
      - ["80:80", "443:443"]
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
